name: Repository Dispatch
on:
  repository_dispatch:
    types: [docs-needed]
jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
      - name: save vars
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
        env: 
          client_payload: ${{ github.event.client_payload }}
      
      - name: write issue
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ACTION_ISSUE_TEMPLATE.md
